sensitivePermissions:
  # Cluster-wide Administrative Access
  - name: "cluster-admin-access"
    apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    impact: "Critical - Full cluster administrative access"
    exceptions:
      users: ["system:admin", "system:masters"]
      serviceAccounts: ["openshift-cluster-version:default"]
      groups: ["system:masters"]

  # Security Context Constraints
  - name: "scc-management"
    apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["create", "delete", "update", "patch"]
    impact: "High - Can modify security policies affecting pod security"
    exceptions:
      serviceAccounts: ["openshift-security:scc-controller"]

  # RBAC Management
  - name: "rbac-management"
    apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["create", "delete", "update", "patch"]
    impact: "High - Can modify access controls and elevate privileges"
    exceptions:
      serviceAccounts: ["openshift-authentication-operator:authentication-operator"]

  # User and Group Management
  - name: "user-management"
    apiGroups: ["user.openshift.io"]
    resources: ["users", "groups", "identities", "useridentitymappings"]
    verbs: ["create", "delete", "update"]
    impact: "High - Can create and modify user accounts"
    exceptions:
      serviceAccounts: ["openshift-authentication-operator:oauth-openshift"]

  # OAuth and Authentication
  - name: "oauth-management"
    apiGroups: ["oauth.openshift.io", "config.openshift.io"]
    resources: ["oauthclients", "authentications", "oauthaccesstokens"]
    verbs: ["create", "delete", "update"]
    impact: "High - Can modify authentication configuration"

  # Secret Management
  - name: "secret-management"
    apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
    impact: "High - Access to sensitive data including credentials"

  # ConfigMap Management
  - name: "configmap-management"
    apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "delete"]
    impact: "Medium - Can modify application configurations"

  # Node Management
  - name: "node-management"
    apiGroups: ["", "machine.openshift.io"]
    resources: ["nodes", "machines", "machinesets"]
    verbs: ["create", "delete", "update", "patch"]
    impact: "High - Can modify cluster infrastructure"

  # Storage Management
  - name: "storage-management"
    apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "persistentvolumes"]
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can modify storage configurations"

  # Network Policy
  - name: "network-policy-management"
    apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can modify network security policies"

  # Project/Namespace Management
  - name: "project-management"
    apiGroups: ["project.openshift.io"]
    resources: ["projects", "projectrequests"]
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can create and modify project isolation"

  # Security Policy Reviews
  - name: "security-policy-review"
    apiGroups: ["security.openshift.io"]
    resources: ["podsecuritypolicyreviews", "podsecuritypolicyselfsubjectreviews"]
    verbs: ["create"]
    impact: "Medium - Can review security policies"

  # Operator Management
  - name: "operator-management"
    apiGroups: ["operators.coreos.com", "config.openshift.io"]
    resources: ["operators", "operatorhubs", "clusterserviceversions"]
    verbs: ["create", "update", "delete"]
    impact: "High - Can modify cluster operators and components"

  # Route Management
  - name: "route-management"
    apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "delete"]
    impact: "Medium - Can expose services externally"

  # Pod Execution
  - name: "privileged-pod-execution"
    apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]
    impact: "High - Can run potentially privileged containers"

  # CSI Driver Management
  - name: "csi-management"
    apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers", "csinodes"]
    verbs: ["create", "update", "delete"]
    impact: "High - Can modify storage drivers"

  # Virtual Machine Management (KubeVirt)
  - name: "vm-management"
    apiGroups: 
      - "kubevirt.io"
      - "snapshot.kubevirt.io"
      - "clone.kubevirt.io"
      - "pool.kubevirt.io"
    resources: 
      - "virtualmachines"
      - "virtualmachineinstances"
      - "virtualmachineinstancemigrations"
      - "virtualmachineinstancereplicasets"
      - "virtualmachinesnapshots"
      - "virtualmachinesnapshotcontents"
      - "virtualmachineclones"
      - "virtualmachinepools"
    verbs: ["create", "delete", "update", "patch"]
    impact: "High - Can manage virtual machines and their lifecycle"
    exceptions:
      serviceAccounts: ["kubevirt-operator:kubevirt-operator"]

  # Virtual Machine Instance Type Management
  - name: "vm-instancetype-management"
    apiGroups: ["instancetype.kubevirt.io"]
    resources: 
      - "virtualmachineinstancetypes"
      - "virtualmachineclusterinstancetypes"
      - "virtualmachinepreferences"
      - "virtualmachineclusterpreferences"
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can modify VM instance types and preferences"

  # Network Attachment Definition Management (Multus)
  - name: "multus-management"
    apiGroups: ["k8s.cni.cncf.io"]
    resources: 
      - "network-attachment-definitions"
      - "networkattachmentdefinitions"
    verbs: ["create", "delete", "update", "patch"]
    impact: "High - Can modify additional network configurations"
    exceptions:
      serviceAccounts: ["multus-operator:multus-operator"]

  # NMState Configuration Management
  - name: "nmstate-management"
    apiGroups: ["nmstate.io"]
    resources: 
      - "nmstates"
      - "nodenetworkconfigurations"
      - "nodenetworkconfigurationpolicies"
      - "nodenetworkconfigurationenactments"
      - "nodenetworkstates"
    verbs: ["create", "delete", "update", "patch"]
    impact: "Critical - Can modify node network configurations"
    exceptions:
      serviceAccounts: ["nmstate-operator:nmstate-operator"]

  # Network State Access
  - name: "network-state-access"
    apiGroups: ["nmstate.io"]
    resources: ["nodenetworkstates"]
    verbs: ["get", "list", "watch"]
    impact: "Low - Can view node network states"

  # Whereabouts IPAM Management
  - name: "ipam-management"
    apiGroups: ["whereabouts.cni.cncf.io"]
    resources: 
      - "ippools"
      - "overlappingrangeipreservations"
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can modify IP address management"

  # VM Storage Management
  - name: "vm-storage-management"
    apiGroups: 
      - "cdi.kubevirt.io"
      - "export.kubevirt.io"
    resources: 
      - "datavolumes"
      - "datasources"
      - "dataimportcrons"
      - "virtualmachineexports"
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can manage VM storage resources"
    exceptions:
      serviceAccounts: ["cdi-operator:cdi-operator"]

  # VM Migration Management
  - name: "vm-migration-management"
    apiGroups: ["migrations.kubevirt.io"]
    resources: ["migrationpolicies"]
    verbs: ["create", "delete", "update"]
    impact: "Medium - Can configure VM migration policies"

  # Host Device Management
  - name: "host-device-management"
    apiGroups: ["kubevirt.io"]
    resources: ["virtualmachineinstancepresets"]
    verbs: ["create", "delete", "update"]
    impact: "High - Can configure VM access to host devices"

  # Network Interface Management
  - name: "network-interface-management"
    apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
    impact: "High - Can modify network interfaces"
    exceptions:
      serviceAccounts: ["multus-operator:multus-operator"]
